cart/urls.py
from django.urls import path

from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import admin_order_pdf, order_create, admin_order_detail

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf')
]

shop/urls.py
from django.urls import path
from shop.views import product_detail, product_list

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail')
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from shop.models import Product

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True })
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'layout/base.html' %}

{% block title %}My Cart{% endblock %}

{% block content %}
<div class="flex flex-col gap-8">
    <header>
        <h1 class="text-3xl">Your shopping cart</h1>
    </header>
    <section class="flex flex-col gap-4">
        <div>
            <table class="">
                <thead>
                    <tr class="w-screen border py-4">
                        <th class="py-4">Image</th>
                        <th class="py-4">Product</th>
                        <th class="py-4">Quantity</th>
                        <th class="py-4">Remove</th>
                        <th class="py-4">Unit price</th>
                        <th class="py-4">Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                        {% with product=item.product %}
                            <tr class="border-b py-4">
                                <td class="py-4 px-4">
                                    <a href="{{ product.get_absolute_url }}">
                                        <img width="200px" src="{{ product.image.url }}" alt="">
                                    </a>
                                </td>
                                <td class="py-4 px-4 line-clamp-2">{{ product.name }}</td>
                                <td class="py-4 px-4">
                                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                        {% csrf_token %}
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.override }}
                                        <input type="submit" value="Update">
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                        <input type="submit" value="Remove">
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td class="py-4 px-4">${{ item.price }}</td>
                                <td class="py-4 px-4">${{ item.total_price }}</td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                    <tr class="border py-4">
                        <td class="py-4 px-4">Total</td>
                        <td colspan="4"></td>
                        <td class="py-4 px-4">${{ cart.get_total_price }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div>
            <p class="flex justify-end items-center gap-4">
                <a href="{% url 'shop:product_list' %}" class="block py-4 px-4 bg-gray-300">Continue shopping</a>
                <a href="{% url 'orders:order_create' %}" class="block py-4 px-4 bg-blue-100">Checkout</a>
            </p>
        </div>
    </section>
</div>
{% endblock %}