cart/urls.py
from django.urls import path

from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import admin_order_pdf, order_create, admin_order_detail

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf')
]

orders/models.py
from django.db import models

from shop.models import Product

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from orders.models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']
        

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.admin.views.decorators import staff_member_required

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string

import weasyprint

from cart.cart import Cart
from orders.forms import OrderCreateForm
from orders.models import Order, OrderItem
from .tasks import order_created

# Create your views here.
def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])

            #clear the cart
            cart.clear()
            order_created.delay(order.id)

            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))

            # return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm()

    return render(request, 'order/create.html', {'form': form, 'cart': cart })


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    return render(request, 'admin/orders/order/detail.html', {
        'order': order
    })

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('order/pdf.html', {
        'order': order
    })

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f"filename=order_{order.id}.pdf"
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')])

    return response

orders/templates/order/create.html
{% extends "layout/base.html" %}

{% block title %}
Checkout
{% endblock %}

{% block content %}
<div class="flex flex-col gap-8">
    <header>
        <h1 class="text-3xl">Checkout</h1>
    </header>
    <section class="flex gap-8">
        <div class="flex-10 w-full">
            <form method="post" class="flex flex-col gap-4">
                <div class="py-2 px-4 border flex flex-col gap-1">
                    <label for="id_first_name">Fistname</label>
                    {{ form.first_name}}
                </div>
                <div class="py-2 px-4 border flex flex-col gap-1">
                    <label for="id_last_name">Lastname</label>
                    {{ form.last_name}}
                </div>
                <div class="py-2 px-4 border flex flex-col gap-1">
                    <label for="id_email">Email</label>
                    {{ form.email}}
                </div>
                <div class="py-2 px-4 border flex flex-col gap-1">
                    <label for="id_address">Address</label>
                    {{ form.address}}
                </div>
                <div class="py-2 px-4 border flex flex-col gap-1">
                    <label for="id_postal_code">Postal Code</label>
                    {{ form.postal_code}}
                </div>
                <div class="py-2 px-4 border flex flex-col gap-1">
                    <label for="id_city">City</label>
                    {{ form.city}}
                </div>
                <div>
                    <input type="submit" value="Place order" class="py-2 px-4 bg-blue-100 cursor-pointer">
                </div>
            {% csrf_token %}
            </form>
        </div>
        <div class="flex flex-col gap-4">
            <header>
                <h3 class="text-2xl">Your order</h3>
            </header>
            <ul class="flex flex-col gap-4">
                {% for item in cart %}
                    <li class="flex items-center gap-4 border py-2 px-4">
                        <picture class="w-10">
                            <img width="100px" src="{{  item.product.image.url }}" alt="">
                        </picture>
                        <div class="flex flex-col gap-2">
                            <div>{{ item.product.name }}</div>
                            <div class="flex items-center gap-2">
                                <div>{{ item.quantity }}x</div>
                                <div>${{ item.total_price }}</div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="flex justify-end items-end">
                <div class="bg-blue-200 py-2 px-4">Total: ${{ cart.get_total_price }}</div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

orders/templates/order/created.html
{% extends "layout/base.html" %}

{% block title %}
Thank you
{% endblock %}

{% block content %}
 <h1>Thank you</h1>
 <p>Your order has been successfully completed. Your order number is
 <strong>{{ order.id }}</strong>.</p>
{% endblock %}

orders/templates/order/pdf.html
<html>
<body>
 <h1>My Shop</h1>
 <p>
 Invoice no. {{ order.id }}</br>
 <span class="secondary">
 {{ order.created|date:"M d, Y" }}
 </span>
 </p>
 <h3>Bill to</h3>
 <p>
    {{ order.first_name }} {{ order.last_name }}<br>
    {{ order.email }}<br>
    {{ order.address }}<br>
    {{ order.postal_code }}, {{ order.city }}
    </p>
    <h3>Items bought</h3>
 <table>
 <thead>
 <tr>
 <th>Product</th>
 <th>Price</th>
 <th>Quantity</th>
 <th>Cost</th>
 </tr>
 </thead>
 <tbody>
 {% for item in order.items.all %}
 <tr class="row{% cycle '1' '2' %}">
 <td>{{ item.product.name }}</td>
 <td class="num">${{ item.price }}</td>
 <td class="num">{{ item.quantity }}</td>
 <td class="num">${{ item.get_cost }}</td>
 </tr>
 {% endfor %}
 <tr class="total">
 <td colspan="3">Total</td>
 <td class="num">${{ order.get_total_cost }}</td>
 </tr>
 </tbody>
 </table>
 <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
    {% if order.paid %}Paid{% else %}Pending payment{% endif %}
    </span>
   </body>
   </html>